%% Copyright (C) 2019 by Jessica Scheick
%% v0.01 15Aug2019
%%
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either version 1.3
%% of this license or (at your option) any later version.
%% The latest version of this license is in
%%   http://www.latex-project.org/lppl.txt
%% and version 1.3 or later is part of all distributions of LaTeX
%% version 2005/12/01 or later.
%%
%% This work has the LPPL maintenance status `maintained'.
%% 
%% The Current Maintainer of this work is Jessica Scheick.
%% Please report problems to: jbscheick-at-gmail-dot-com
%%
%% This work consists of this file (ROSES-NASA-proposal.cls) and the associated file (ROSES-NASA-proposal_template.tex)
%%


\ProvidesClass{ROSES-NASA-proposal}[2019-08-15]
\NeedsTeXFormat{LaTeX2e}

\LoadClass[letterpaper,12pt]{article}
\RequirePackage[margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{color, soul}
